# This file was generated by GoReleaser. DO NOT EDIT.
cask "bggclient" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "86c331e9c372467b3dcc67528e2d09b3416c37f3115fc969c432d32dbcaee391"
      url "https://github.com/richardwooding/bggclient/releases/download/v#{version}/bggclient_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a8999b9c7a9d2671e31f57261c9521bebad53898f1ffddf9ae7c834cc9fd943"
      url "https://github.com/richardwooding/bggclient/releases/download/v#{version}/bggclient_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1ccaefed7901da945979ba42d7ba7ee47279ab8add299186edfc7623644b3054"
      url "https://github.com/richardwooding/bggclient/releases/download/v#{version}/bggclient_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c236f9e25bd329ea9ae70fcb2ad563190a4b46aa6c41e2e56c911de910b01da"
      url "https://github.com/richardwooding/bggclient/releases/download/v#{version}/bggclient_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bggclient"
  desc "BoardGameGeek XML API client — CLI and MCP server"
  homepage "https://richardwooding.github.io/bggclient/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bggclient"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bggclient"]
    end
  end

  # No zap stanza required

end
