# This file was generated by GoReleaser. DO NOT EDIT.
cask "bggclient" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "48c8de42ae66e477e8b944ef6c78b8df58c63fea8c715e7bae99869a3ed21909"
      url "https://github.com/richardwooding/bggclient/releases/download/v#{version}/bggclient_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf782f1593f70936683a9c245406e6e1765e06006b4de280af8843a87ca73a2c"
      url "https://github.com/richardwooding/bggclient/releases/download/v#{version}/bggclient_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "40494204aa030f641d99141a615a07b7df8e6d305674e4208ddfccc8e79e2c92"
      url "https://github.com/richardwooding/bggclient/releases/download/v#{version}/bggclient_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a6f5e1311fb1acdbcc83744ae7779165b1dcac66402328b62f5dca91c48bbb1e"
      url "https://github.com/richardwooding/bggclient/releases/download/v#{version}/bggclient_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bggclient"
  desc "BoardGameGeek XML API client — CLI and MCP server"
  homepage "https://richardwooding.github.io/bggclient/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bggclient"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bggclient"]
    end
  end

  # No zap stanza required

end
