# This file was generated by GoReleaser. DO NOT EDIT.
cask "c2pa-mcp" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "62c11eb793f92bf3c836bcb149ccacd7d4655264f86de8c1dc63806d517c0d2a"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5cbc36805ad6c6a4ffb9f9ec925ddbd81eb85d7366e202c8622a4fadbecafd6b"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4f3bf2356905a48304eec2282ef31040885c90a3544ee2f0ede791ed2c366aed"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1ea30deca19957aa80a0804461367aaba53eea1b25dfcd7028eb1c5fa6c6a5df"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "c2pa-mcp"
  desc "CLI and MCP server for reading, validating and signing C2PA / Content Credentials in JPEG, PNG, WebP, GIF, TIFF, HEIC, AVIF, SVG, MP4, MOV, AVI, WAV, MP3 and PDF"
  homepage "https://github.com/richardwooding/c2pa-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c2pa-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/c2pa-mcp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    c2pa-mcp is not yet signed/notarized with an Apple Developer ID. The cask
    removes the quarantine attribute on install so Gatekeeper lets it run. If
    macOS still blocks it, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/c2pa-mcp
  EOS
end
