# This file was generated by GoReleaser. DO NOT EDIT.
cask "c2pa-mcp" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "5e52a3829fede589b23508a13c20aadc4099f07d08b75fa1c85b8aa6dc4bafcc"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "133a032fc097f83871ebd7fa2ba407b6ed12db418f802d6fe7f2b553e2972648"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "edbcbf80bf23f8eeb660af4b1bc8430a6e1ce2d954849327a61b89bd130c9e8e"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a21ef528bea65c757dc4656251dc9115697e02147c9ef4533bbef711526af6b9"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "c2pa-mcp"
  desc "CLI and MCP server for reading and validating C2PA / Content Credentials in JPEG and PNG"
  homepage "https://github.com/richardwooding/c2pa-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c2pa-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/c2pa-mcp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    c2pa-mcp is not yet signed/notarized with an Apple Developer ID. The cask
    removes the quarantine attribute on install so Gatekeeper lets it run. If
    macOS still blocks it, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/c2pa-mcp
  EOS
end
