# This file was generated by GoReleaser. DO NOT EDIT.
cask "c2pa-mcp" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "f88441f16f894039ee5f4db688d6fcf4252f8790a63b01963ea4f786b5934359"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dfa8d3587a1bc9eb95b1c489205977981b390f4ea866519ccfe7e6a63327add1"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d14ebd0973f297fc86b4b0dbe571aaadfeb96847bb0fd8e609c61a6fc054d05d"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a88a3402ff1fd967bf79f2dbc34abbfbd246b255eaa988f8d920fa5adb20dcf"
      url "https://github.com/richardwooding/c2pa-mcp/releases/download/v#{version}/c2pa-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "c2pa-mcp"
  desc "CLI and MCP server for reading, validating and signing C2PA / Content Credentials in JPEG, PNG, WebP, GIF, TIFF, HEIC, AVIF, SVG, MP4, MOV, AVI, WAV, MP3 and PDF"
  homepage "https://github.com/richardwooding/c2pa-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c2pa-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/c2pa-mcp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    c2pa-mcp is not yet signed/notarized with an Apple Developer ID. The cask
    removes the quarantine attribute on install so Gatekeeper lets it run. If
    macOS still blocks it, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/c2pa-mcp
  EOS
end
