# This file was generated by GoReleaser. DO NOT EDIT.
cask "capetown-opendata-mcp" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "0d0ce93d23c97e3ac7ccc806574dd242cc77fd44d98ccb9aad6060610095e6ce"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "79bfebfebb42819916c3064157e6c74a775a3fe3ad87a70ae38f8fe640c793d9"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8316d28d026285dc187aebeb46200ec8c2e274c548830850950365facd18f267"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ae68367c3af8ea44f307507b55404c890acd91ac149485cad10e9ecf81aa024"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "capetown-opendata-mcp"
  desc "MCP server for the City of Cape Town Open Data Portal"
  homepage "https://github.com/richardwooding/capetown-opendata-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capetown-opendata-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capetown-opendata-mcp"]
    end
  end

  # No zap stanza required

end
