# This file was generated by GoReleaser. DO NOT EDIT.
cask "capetown-opendata-mcp" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "5294ec484690968a8697b416319b62d2959283ad7c11349c1dc9ab0b3ff8fd27"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fe680672223ef534908f1957e3fcefa4f05ea9013a90894e37a1b410729b9992"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3b7efdf881951a82251ad3c6bdf2a57a4b8f0e0550ea7d02e9d79e9674de9e9b"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2fc89b478eb6bff90245c260de8e45acf9fb1e9ba96ac4897a292249a2b1d5c1"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "capetown-opendata-mcp"
  desc "MCP server for the City of Cape Town Open Data Portal"
  homepage "https://github.com/richardwooding/capetown-opendata-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capetown-opendata-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capetown-opendata-mcp"]
    end
  end

  # No zap stanza required

end
