# This file was generated by GoReleaser. DO NOT EDIT.
cask "capetown-opendata-mcp" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "de7522bc6c560f4ba17e3338b9af9a4889e68ee10b9492fcdd9e1e8c3c8f4639"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "44378af425d1e7aab23be6c13e7787b3eaa20eeb04caf1b23c1d6c6105785d5e"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "068c64bdd4391525e43f2a50a200fd11426876d415ba6021a160d724568024a9"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5db47ec6cb765b635131918c5206f85dc53a852e78f58961ef6dbe3cc996194e"
      url "https://github.com/richardwooding/capetown-opendata-mcp/releases/download/v#{version}/capetown-opendata-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "capetown-opendata-mcp"
  desc "MCP server for the City of Cape Town Open Data Portal"
  homepage "https://github.com/richardwooding/capetown-opendata-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capetown-opendata-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capetown-opendata-mcp"]
    end
  end

  # No zap stanza required

end
