# This file was generated by GoReleaser. DO NOT EDIT.
cask "codemetrics" do
  version "0.13.1"

  on_macos do
    on_arm do
      sha256 "3e973a8ad174acfe222611b0eeecb43a5577a6453f7039435755be33a5d15eda"
      url "https://github.com/richardwooding/codemetrics/releases/download/v#{version}/codemetrics_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee18c15a63ec9b124b192484a6af81a90812fff521c3780d4f588b63733af0a6"
      url "https://github.com/richardwooding/codemetrics/releases/download/v#{version}/codemetrics_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "48dbc89bd7ec061806fc245369b24ce026257495490403c66c043710f778b427"
      url "https://github.com/richardwooding/codemetrics/releases/download/v#{version}/codemetrics_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7483f57d2b9c87e0e826bdf54ad8bfd58bfbac0a5b3e39e520a6db0f91e8b40e"
      url "https://github.com/richardwooding/codemetrics/releases/download/v#{version}/codemetrics_#{version}_linux_amd64.tar.gz"
    end
  end

  name "codemetrics"
  desc "Per-function cyclomatic and cognitive complexity with SARIF output and a baseline quality gate"
  homepage "https://github.com/richardwooding/codemetrics"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codemetrics"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codemetrics"]
  end

  # No zap stanza required
end
