# This file was generated by GoReleaser. DO NOT EDIT.
cask "codemetrics" do
  version "0.12.2"

  on_macos do
    on_intel do
      sha256 "172462df195f41e6c54656307483c8f1350b7b2c849f4fce56167b959a269644"
      url "https://github.com/richardwooding/codemetrics/releases/download/v#{version}/codemetrics_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbf34d15eb7295a180a2cc7be4d54bc9fa4f1bfb00025c52468f00d90f43cf6e"
      url "https://github.com/richardwooding/codemetrics/releases/download/v#{version}/codemetrics_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "862693f262e6ce42ec3ee8d00984cb0347b6d5a5dd692879ffaaa835fb0b99ce"
      url "https://github.com/richardwooding/codemetrics/releases/download/v#{version}/codemetrics_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e2ebf947cf2fd4ac37e256bf1ba33711c64c37b3fd7f0af3c6bdd828269c314"
      url "https://github.com/richardwooding/codemetrics/releases/download/v#{version}/codemetrics_#{version}_linux_arm64.tar.gz"
    end
  end

  name "codemetrics"
  desc "Per-function cyclomatic and cognitive complexity with SARIF output and a baseline quality gate"
  homepage "https://github.com/richardwooding/codemetrics"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codemetrics"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codemetrics"]
  end

  # No zap stanza required

end
