# This file was generated by GoReleaser. DO NOT EDIT.
cask "codemetrics" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "f6bb18975f926e12c6a849933e4b12593ce67b4bb381f8e2300a413759bddbde"
      url "https://github.com/richardwooding/go-codemetrics/releases/download/v#{version}/codemetrics_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f56a158b855808b3434ad2984c898a0ba9fd2348aef4b61219fd50e8054efb09"
      url "https://github.com/richardwooding/go-codemetrics/releases/download/v#{version}/codemetrics_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e6dddd7e1e94f521117e276a20985a8eaa9491943003f55f82c1050de69724c6"
      url "https://github.com/richardwooding/go-codemetrics/releases/download/v#{version}/codemetrics_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a12aa833fb62e82fa67e3f9364a6c459d84d9aef48dd2ce8b1cb6583b70b323c"
      url "https://github.com/richardwooding/go-codemetrics/releases/download/v#{version}/codemetrics_#{version}_linux_arm64.tar.gz"
    end
  end

  name "codemetrics"
  desc "Per-function cyclomatic and cognitive complexity with SARIF output and a baseline quality gate"
  homepage "https://github.com/richardwooding/go-codemetrics"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codemetrics"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codemetrics"]
  end

  # No zap stanza required

end
