# This file was generated by GoReleaser. DO NOT EDIT.
cask "feed-mcp" do
  version "2.6.2"

  on_macos do
    on_intel do
      sha256 "431c979bfa7e1293ed03d72fb09c0409215e4c9f5e0f8e07812ee69b9c684c92"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0cc479e8a0706f1f3ead5bd7a8401f76d8b82fee36d79270cca6a5ee46c6e803"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b09ba49a7d0ff0b1a520776f6417cfc9daca575239d23b83a066a8a47f6732ae"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3872c73a81734ef6cb01110a6549f402aa4bf33e3105b677d8355ee302dd9c6a"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Linux_arm64.tar.gz"
    end
  end

  name "feed-mcp"
  desc "MCP server that fetches RSS/Atom/JSON feeds and serves them to AI assistants"
  homepage "https://github.com/richardwooding/feed-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "feed-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/feed-mcp"]
    end
  end

  # No zap stanza required

end
