# This file was generated by GoReleaser. DO NOT EDIT.
cask "feed-mcp" do
  version "2.6.6"

  on_macos do
    on_intel do
      sha256 "b84871be94a5f3926bb82a6fa15759ad56931ab3373578f57e78ccdf112ddc02"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "03a2671803180f3fbac1fb5786f23d9d5083b8faef8de6511be9e099d2bd19fd"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "042fb3f56870530dd72980b503f2d211a6e6c0b576e39e58be5d83271dd211ac"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e988f630ff01faf3943bf6a96fdf92076404f3adcec5ce73ef82516b694f85e8"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Linux_arm64.tar.gz"
    end
  end

  name "feed-mcp"
  desc "MCP server that fetches RSS/Atom/JSON feeds and serves them to AI assistants"
  homepage "https://github.com/richardwooding/feed-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "feed-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/feed-mcp"]
    end
  end

  # No zap stanza required

end
