# This file was generated by GoReleaser. DO NOT EDIT.
cask "feed-mcp" do
  version "2.6.13"

  on_macos do
    on_arm do
      sha256 "7be80dfcab5ff238d0b22adda9ea13de684dde1b3ced905d69507571d2c33d2f"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "920aa1d49a972a5f45e9939732102b41843ad5cd75dcfc05ae26a2879e59e4f5"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "525931ad0bbfc905cafaa2d3e1a9e31dc94d6736d853d300c45bf3f0f5640179"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bbc4a02d44baa49deba0786e570c6b226731b28d515775eefcb06a60505bd9a7"
      url "https://github.com/richardwooding/feed-mcp/releases/download/v#{version}/feed-mcp_Linux_x86_64.tar.gz"
    end
  end

  name "feed-mcp"
  desc "MCP server that fetches RSS/Atom/JSON feeds and serves them to AI assistants"
  homepage "https://github.com/richardwooding/feed-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "feed-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/feed-mcp"]
    end
  end

  # No zap stanza required
end
