# This file was generated by GoReleaser. DO NOT EDIT.
cask "file-search-on" do
  version "0.76.0"

  on_macos do
    on_intel do
      sha256 "42b5b619ebcce9852bbb640d55b5a5dc018f483e8455eb514635fe12d0e2cd0d"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "46c9e9c3b230e1ec3d73a97951b1fc794a365e3f062a9eb96bfe87ca8f12bba7"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ed626b4579f053d3b0db044dbc88bf9c8f69b6909e3128005ee83aa99450368c"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d5eb87e90b3c608dcaae9e0e89f21697719382039792aec3c19c4235ac0bdb77"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_linux_arm64.tar.gz"
    end
  end

  name "file-search-on"
  desc "Content-type aware file search with CEL attribute filtering"
  homepage "https://github.com/richardwooding/file-search-on"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "file-search-on"
  binary "file-search-on-ocr-helper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/file-search-on"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/file-search-on-ocr-helper"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    file-search-on is not yet signed/notarized with an Apple Developer ID.
    The cask removes the quarantine attribute from file-search-on AND
    file-search-on-ocr-helper on install so Gatekeeper lets them run
    (the helper is what powers --ocr; it's spawned as a subprocess
    and inherits the quarantine state from the install tarball). If
    macOS still blocks anything, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/file-search-on
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/file-search-on-ocr-helper
  EOS
end
