# This file was generated by GoReleaser. DO NOT EDIT.
cask "file-search-on" do
  version "0.81.0"

  on_macos do
    on_intel do
      sha256 "19ddca0fc314c852091722a056e3682d8f165438f0f7db57c5c2c208a412fe99"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a9e81644a318b95062cb55061b8afd8fc93cd7cfe4d9f8f2d1e09302ebcac87"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "938ae0aae4a63801e2f71f3d2602fc2f1e0c84fddde758b4730e3fdbd73e6bed"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7302b6def08838f4d4207e305d796c42b198be00bee9bc23b3dd1b47f4a3093b"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_linux_arm64.tar.gz"
    end
  end

  name "file-search-on"
  desc "Content-type aware file search with CEL attribute filtering"
  homepage "https://github.com/richardwooding/file-search-on"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "file-search-on"
  binary "file-search-on-ocr-helper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/file-search-on"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/file-search-on-ocr-helper"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    file-search-on is not yet signed/notarized with an Apple Developer ID.
    The cask removes the quarantine attribute from file-search-on AND
    file-search-on-ocr-helper on install so Gatekeeper lets them run
    (the helper is what powers --ocr; it's spawned as a subprocess
    and inherits the quarantine state from the install tarball). If
    macOS still blocks anything, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/file-search-on
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/file-search-on-ocr-helper
  EOS
end
