# This file was generated by GoReleaser. DO NOT EDIT.
cask "file-search-on" do
  version "0.33.0"

  on_macos do
    on_intel do
      sha256 "6a85ecff6aad0d94b51f32045f56779facf237549cdc3093bd153f7250513303"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ba2ff8a414cb23d77b42300e3b0be225fd765ede99cfcc5d8cc96f410e24c03"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9b4d3013fbdd388367d76d34d4a96ac699d794831a49dffedb78a64e4884b7c3"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f13327d3ae80454a7c39a3f0c2f7e2ea3c2ee3f51d545542ee15b89ba97a5126"
      url "https://github.com/richardwooding/file-search-on/releases/download/v#{version}/file-search-on_#{version}_linux_arm64.tar.gz"
    end
  end

  name "file-search-on"
  desc "Content-type aware file search with CEL attribute filtering"
  homepage "https://github.com/richardwooding/file-search-on"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "file-search-on"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/file-search-on"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    file-search-on is not yet signed/notarized with an Apple Developer ID.
    The cask removes the quarantine attribute on install so Gatekeeper
    lets it run. If macOS still blocks it, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/file-search-on
  EOS
end
