# This file was generated by GoReleaser. DO NOT EDIT.
cask "forge" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "e84ffda36cbeb4f1db068eb51ff9373bc892adebde0c83d05cbe3b8b529c2b8b"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e22180586ede5fbadc43f0a13a4b16a9bf4aff654d2485c1c53de7a2a8552562"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5e51bb728adabeb298f4b3d30a73b978b36bf9c712ad3857eb7d673c070668cd"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7ab241df1bfe52732282153a1d743bd1fe838ea0c911ffbce0520dd2cc9a029"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "forge"
  desc "Compile Go programs to sandboxed WebAssembly tools, exposed over CLI, REPL, MCP, REST and gRPC at once"
  homepage "https://github.com/richardwooding/forge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forge"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    forge is not yet signed or notarized with an Apple Developer ID; the cask
    removes the quarantine attribute on install. If macOS still blocks it:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/forge

    Building a tool needs a Go toolchain on PATH: `forge tool add` compiles
    the source to WebAssembly with it. Running an already-installed tool does
    not. `forge doctor` says which of those you have.
  EOS
end
