# This file was generated by GoReleaser. DO NOT EDIT.
cask "forge" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "e2a454630102c47c0025e02f8a754e7829545a6b141bb410b8275fdb8d1ef2f9"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0181ca2c592a0948fc061d8d5696c6fe2ae1b08745f4422b29a979a6d9cbf493"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b833e00dd5cfb86e8afb673591231c4d988c044e8cd62ab281f2745f68ecdfaa"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "69b0331dc32e367e875a68cd7d3a55169c92c72b7c9321b0729b644866f4c28a"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "forge"
  desc "Compile Go programs to sandboxed WebAssembly tools, exposed over CLI, REPL, MCP, REST and gRPC at once"
  homepage "https://github.com/richardwooding/forge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forge"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    forge is not yet signed or notarized with an Apple Developer ID; the cask
    removes the quarantine attribute on install. If macOS still blocks it:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/forge

    Building a tool needs a Go toolchain on PATH: `forge tool add` compiles
    the source to WebAssembly with it. Running an already-installed tool does
    not. `forge doctor` says which of those you have.
  EOS
end
