# This file was generated by GoReleaser. DO NOT EDIT.
cask "forge" do
  version "0.14.0"

  on_macos do
    on_arm do
      sha256 "d1d931f6fe3e348a6bb0f9297adc0161cc4cdd8af39bdb9c5287b535778297e8"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a20ff41cffd393814bdeebdbe3ea2205fae79c1e502459e23614a9b2e8a6efbc"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5fc590866ba675cf2c6ffe97ccd24333e6cdac1e9a09b37df1bd70a79724aa54"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b811e1e89b76059ed2de8d79d922d8628fc5431f4c526589c553cddb7a071f7"
      url "https://github.com/richardwooding/forge/releases/download/v#{version}/forge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "forge"
  desc "Compile Go programs to sandboxed WebAssembly tools, exposed over CLI, REPL, MCP, REST and gRPC at once"
  homepage "https://github.com/richardwooding/forge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forge"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    forge is not yet signed or notarized with an Apple Developer ID; the cask
    removes the quarantine attribute on install. If macOS still blocks it:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/forge

    Building a tool needs a Go toolchain on PATH: `forge tool add` compiles
    the source to WebAssembly with it. Running an already-installed tool does
    not. `forge doctor` says which of those you have.
  EOS
end
