# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitlapse" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "606b67b7911516030336497c8db6af89f3e9b7945fcb55a7dde429be9342f37a"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca438a68f6905e5acbd736673d6262c90d4a7921e9a970e149d3b4c16e951442"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7395960f8d30dc0747b3cc2d13a96513544b29fc25e06ffb921c6f42178202cc"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3127ef6fb1cf2a7efce856d02b64c25981ea3a9405964f2a9c6716b7c3ca345"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitlapse"
  desc "Replay a git repository's complexity history as a terminal timelapse"
  homepage "https://github.com/richardwooding/gitlapse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitlapse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitlapse"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    gitlapse is not yet signed/notarized with an Apple Developer ID. The cask
    removes the quarantine attribute on install so Gatekeeper lets it run. If
    macOS still blocks it, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/gitlapse
  EOS
end
