# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitlapse" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "9e4e9aeff6694f7e0f1a171be5966dbd7e8ceb781c16998682aad9c12016eec3"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ca3bc1be1848feea169fb0cbd0fe507a0cd4ae8bf7af63b2295d0aa19519206"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f33c27d423329e29543c6e51f4dc074c2338f02a681796029bc49f972af65e9"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c3aa64c43998b931bcd5a0489b7b94646f769cbbeadee96f1afd65fb41ba835a"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitlapse"
  desc "Replay a git repository's complexity history as a terminal timelapse"
  homepage "https://github.com/richardwooding/gitlapse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitlapse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitlapse"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    gitlapse is not yet signed/notarized with an Apple Developer ID. The cask
    removes the quarantine attribute on install so Gatekeeper lets it run. If
    macOS still blocks it, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/gitlapse
  EOS
end
