# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitlapse" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "58ea5357357b9bc032320ac97b6ebb720871c51982093c8c81ef4c08feaeeb31"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "90311e309e814d9557383d372ef2211cad2ca07cb5c70d80b10a86c5c5192194"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bc87059ed990a4d55225e76c421ecbf4cc7fa6936613606378b1c29a61e426c5"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "861ab8179c9739487fb3154cfae2c3020ac89fa516b5f487eedf355f5d844db6"
      url "https://github.com/richardwooding/gitlapse/releases/download/v#{version}/gitlapse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitlapse"
  desc "Replay a git repository's complexity history as a terminal timelapse"
  homepage "https://github.com/richardwooding/gitlapse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitlapse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitlapse"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    gitlapse is not yet signed/notarized with an Apple Developer ID. The cask
    removes the quarantine attribute on install so Gatekeeper lets it run. If
    macOS still blocks it, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/gitlapse
  EOS
end
