# This file was generated by GoReleaser. DO NOT EDIT.
cask "hotspot" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "88fef20e248dc2f98d63c6085c476090bdba03e9f48383286ec0e1fbc1c07733"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "108a08a9e9abaa0279a1bfac61c8ac9f3c691395529bd3315297cc2821bbf75a"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3344a01ff0d4d14b7b4ef1b3b13a9e46cd29b2ecc43eecef45e95e27b28bda67"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "23c0d2cf5893b7d33e689f7bc9e0881fcc7b463e2c2592c1690ef4bc0dfa7ff7"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hotspot"
  desc "Rank a repository by refactoring risk — git churn × complexity × coupling — across 17 languages"
  homepage "https://github.com/richardwooding/hotspot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hotspot"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hotspot"]
  end

  # No zap stanza required

end
