# This file was generated by GoReleaser. DO NOT EDIT.
cask "hotspot" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "57099283e45d4dbe650b20477af31a5ef00176c5493a500d62d1ee0dcb6573b1"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c5f4f4a14dffe06562588b2f45347b904e9c649d6fefd8b8107c7959a61cb8e"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6cf443f59e509f8fb2989b97bd74576a15acb6cf3dfffe47996b28cc9334d1fe"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dc1b61d4f8cc973afad5944af1452a637a9921178397640a6fd5d690d0f296ac"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hotspot"
  desc "Rank a repository by refactoring risk — git churn × complexity × coupling — across 17 languages"
  homepage "https://github.com/richardwooding/hotspot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hotspot"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hotspot"]
  end

  # No zap stanza required
end
