# This file was generated by GoReleaser. DO NOT EDIT.
cask "hotspot" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f39135658ba4d61046e9bac8982af3dd10a3408298299bde8d011b48b26a98f6"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa2db8a909b8b319914a5a1471fa6e389c1063fa4939fa44ff62d35fb54d60ab"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ebe7ba00a30889c3737a6882b153615f4f09aa18708d91dd30df5c9e3e969b8c"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3807a165f26ef181994dd647ad8360296212238ed391f4f088ea9dfdf48448f3"
      url "https://github.com/richardwooding/hotspot/releases/download/v#{version}/hotspot_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hotspot"
  desc "Rank a repository by refactoring risk — git churn × complexity × coupling — across 17 languages"
  homepage "https://github.com/richardwooding/hotspot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hotspot"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hotspot"]
  end

  # No zap stanza required

end
