# This file was generated by GoReleaser. DO NOT EDIT.
cask "kin" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "21751592f6e51b7796828601c04dd8c97b3ab8447a247f0cf79d35cd12e1e4a7"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d120d48819f0c90aad33a2d011e5b3b6ce05b2ce9aafa80d2eae306b99fe4c5b"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a3dc32c274b7af54c9bb2985133908949a3bd3c063da9e675da5f5d0b741736b"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c99332e8efa48bfc069be2fd1a15d3db700d2f1041d7652dafee5ae65d120d08"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kin"
  desc "Command-line ancestry toolkit: WikiTree, eGGSA, NAAIRS and Wikidata into one kinship graph, with relationship labels, an ancestry page and printable reports"
  homepage "https://github.com/richardwooding/kin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kin"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    kin is not yet signed/notarized with an Apple Developer ID. The cask
    removes the quarantine attribute on install so Gatekeeper lets it run. If
    macOS still blocks it, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/kin
  EOS
end
