# This file was generated by GoReleaser. DO NOT EDIT.
cask "kin" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "a2efafd1ca82bc7b02c2179637dbd0b0c9cc0484cb9cb7bcbe5798c3acb455b4"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2c92ac1179ea09fb6f3b51393813aad3a11a158d71da1ed71a249882046c3bed"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c5a4d16086091fd884493beb2c16f717e063b74796104477927bafe7327efa63"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ab3bc2bd054421f18612cf71f56bc3aa5982398e351d5651d6c6ef5b0800f4c0"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kin"
  desc "Command-line ancestry toolkit: WikiTree, eGGSA, NAAIRS and Wikidata into one kinship graph, with relationship labels, an ancestry page, a family tree and printable reports"
  homepage "https://github.com/richardwooding/kin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kin"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    kin is not yet signed/notarized with an Apple Developer ID. The cask
    removes the quarantine attribute on install so Gatekeeper lets it run. If
    macOS still blocks it, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/kin
  EOS
end
