# This file was generated by GoReleaser. DO NOT EDIT.
cask "kin" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "9a72b75d6cc3a5a8fefad3ba378e90f2ba265696a89118a1770dbbb20bbe6da5"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ff94f919a88fb64f1d80bd30fa65b63e75960399c470b9eeeaa5e9ec6845880"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "99bec3ae3fcc2ada563047fda19b0c798076f1a4deebf3180e0efb86c496516d"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "554eacd689f097e9c93ab8adce49f083d3e89a30cf8499266b16318b3a112fce"
      url "https://github.com/richardwooding/kin/releases/download/v#{version}/kin_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kin"
  desc "Command-line ancestry toolkit: WikiTree, eGGSA, NAAIRS and Wikidata into one kinship graph, with relationship labels, an ancestry page, a family tree and printable reports"
  homepage "https://github.com/richardwooding/kin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kin"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    kin is not yet signed/notarized with an Apple Developer ID. The cask
    removes the quarantine attribute on install so Gatekeeper lets it run. If
    macOS still blocks it, run:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/kin
  EOS
end
