# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelfofshame" do
  version "0.3.5"

  on_macos do
    on_intel do
      sha256 "3fae5e27bdeae81ccbabb934a98ce2379039e488f1e0e076438e66a5da786e54"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c48d9b225f2e45f76478a020dc608f8eb514cada5f7c66e6ccc28b7e01b95738"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "24a724489fbe50a707cb74a4d8cc21b6f79d5c7a4c257d00295d220fe5dc4cb6"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be5d6950f75c53c1034751a73b2764b554ec6bbda2e7c8182ac6cf4677d97301"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_linux_arm64.tar.gz"
    end
  end

  name "shelfofshame"
  desc "BoardGameGeek XML API client — CLI and MCP server"
  homepage "https://richardwooding.github.io/shelfofshame/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shelfofshame"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shelfofshame"]
    end
  end

  # No zap stanza required

end
