# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelfofshame" do
  version "0.3.4"

  on_macos do
    on_intel do
      sha256 "6019ef97e5233bf6cd679b4e24174f3fa61711857f6992b4c9c02baac0e2d07d"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "01dcfcf3f0542883767d2fc4740d961bf34c04d6103bcaf24e994b6db5087a02"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eb87180118b72e00e9a4143463bf1c770b298f3c354e29794fc9257dc65528d5"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f74951378e378d460bb4cb13bc3764c9d1f5e63ee58308479d35089af729f9f"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_linux_arm64.tar.gz"
    end
  end

  name "shelfofshame"
  desc "BoardGameGeek XML API client — CLI and MCP server"
  homepage "https://richardwooding.github.io/shelfofshame/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shelfofshame"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shelfofshame"]
    end
  end

  # No zap stanza required

end
