# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelfofshame" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "d48a5c882cf6994269a51e9bcb36998c96be59a47285535d30165869a1f5b313"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e02de1ff8d6403ee78217ad3b76cb14db7bd3df5067f5f10aa45ad4274229d3c"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "da81562803a0991a4e23c6504f4a6b6a3dd7e2212da127d6735b1ba45a74b5a1"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7149fbc15af994807d1590eabb41cbc96aacadd575533d2240163fc86101dd4"
      url "https://github.com/richardwooding/shelfofshame/releases/download/v#{version}/shelfofshame_#{version}_linux_amd64.tar.gz"
    end
  end

  name "shelfofshame"
  desc "BoardGameGeek XML API client — CLI and MCP server"
  homepage "https://richardwooding.github.io/shelfofshame/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shelfofshame"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shelfofshame"]
    end
  end

  # No zap stanza required
end
