# This file was generated by GoReleaser. DO NOT EDIT.
cask "wright" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "28e3256b184e8a162b87e6fab81cd5d728a533dde1eac462f64f4656fec32cc3"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b2189b72e9a46cacf4de9932a426af3bd71083deb023c0d2237b17372be45811"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fe133caebc62e17886763f655d408d5a6c71e1c9dbde199396464b48fc604115"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f98b6bef9ec5c14decbaedc8b0a3b1e8b1b22892033b90b68110f3c58b67b399"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wright"
  desc "Coding-agent terminal harness with approval-first permissions, an OS sandbox and an audit trail"
  homepage "https://richardwooding.github.io/wright/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wright"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wright"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    wright is not yet signed/notarized with an Apple Developer ID; the cask
    removes the quarantine attribute on install. If macOS still blocks it:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/wright

    On macOS the OS sandbox backend is "none" in this release (seatbelt
    profile ships in v0.1.x); shell commands are governed by policy only.
    Run `wright doctor` to see what is active.
  EOS
end
