# This file was generated by GoReleaser. DO NOT EDIT.
cask "wright" do
  version "0.8.3"

  on_macos do
    on_arm do
      sha256 "2de27f76a955414d167c3232a757b6e8e7a89a5e01a71cf15b3d1735f4a7ae67"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6ec3fc91f873bbcef1b3ee10dee542e3b13a83ff3cf46dc8703e6133ab89f116"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7943bfd21f474ac9cf6c91a896b8f5ad4bccd1cd2155a722a2b9b54a55c4cd71"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b30757f4932deb5eeac155dc81603855c6299d272f92866b741f2e3c64f7c34f"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wright"
  desc "Coding-agent terminal harness with approval-first permissions, an OS sandbox and an audit trail"
  homepage "https://richardwooding.github.io/wright/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wright"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wright"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    wright is not yet signed/notarized with an Apple Developer ID; the cask
    removes the quarantine attribute on install. If macOS still blocks it:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/wright

    On macOS the OS sandbox backend is "none" in this release (seatbelt
    profile ships in v0.1.x); shell commands are governed by policy only.
    Run `wright doctor` to see what is active.
  EOS
end
