# This file was generated by GoReleaser. DO NOT EDIT.
cask "wright" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "62b4f4915d2fdc8aa529c7552bad06209a912ee3da6d57be08421fbe9e2b5604"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0eb6aed77faca38cdd9bbfcb01f8154065a269f54b5feca4bcbee9c27be71abc"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6b72d05df3c9f4ebbee99c974120559c1f64821f9e4393356ab0792717cd13d7"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0779f3c3f98f92d2fdb6deb5310ada5ccb19a89fe5e595480923fd323b71cf3a"
      url "https://github.com/richardwooding/wright/releases/download/v#{version}/wright_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wright"
  desc "Coding-agent terminal harness with approval-first permissions, an OS sandbox and an audit trail"
  homepage "https://richardwooding.github.io/wright/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wright"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wright"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    wright is not yet signed/notarized with an Apple Developer ID; the cask
    removes the quarantine attribute on install. If macOS still blocks it:
      sudo xattr -dr com.apple.quarantine $(brew --prefix)/bin/wright

    On macOS the OS sandbox backend is "none" in this release (seatbelt
    profile ships in v0.1.x); shell commands are governed by policy only.
    Run `wright doctor` to see what is active.
  EOS
end
