# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Txtr < Formula
  desc "GNU strings clone written in Go - extracts printable strings from binary files"
  homepage "https://github.com/richardwooding/txtr"
  version "2.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/richardwooding/txtr/releases/download/v2.8.0/txtr_2.8.0_darwin_amd64.tar.gz"
      sha256 "baccd2e35ff278426ae471ed878e5b2068086dc7baa6376321bd62b1ea544a2f"

      def install
        bin.install "txtr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/richardwooding/txtr/releases/download/v2.8.0/txtr_2.8.0_darwin_arm64.tar.gz"
      sha256 "4d9113795927c34f01d663c2d2cc8f7302ad4b1ace2e4a1a1c9170c59b5d98a1"

      def install
        bin.install "txtr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardwooding/txtr/releases/download/v2.8.0/txtr_2.8.0_linux_amd64.tar.gz"
      sha256 "93772e0ce49b0170d6d3cca4fd05ff71557b233615389ec310bc13eea42bfbe7"
      def install
        bin.install "txtr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/richardwooding/txtr/releases/download/v2.8.0/txtr_2.8.0_linux_armv6.tar.gz"
      sha256 "7b06810f0bc05774029e8c31de04ee9eefec89448a8af03eda489753eeb4fcbc"
      def install
        bin.install "txtr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardwooding/txtr/releases/download/v2.8.0/txtr_2.8.0_linux_arm64.tar.gz"
      sha256 "e4648ae169295900618c280efcf0bdc17e485674518c9c6a54f0d47584be0466"
      def install
        bin.install "txtr"
      end
    end
  end

  test do
    system "#{bin}/txtr --version"
  end
end
