# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Txtr < Formula
  desc "GNU strings clone written in Go - extracts printable strings from binary files"
  homepage "https://github.com/richardwooding/txtr"
  version "2.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/richardwooding/txtr/releases/download/v2.7.2/txtr_2.7.2_darwin_amd64.tar.gz"
      sha256 "3e5c53203df015c5c38358e740cd906df1a2562a1f3ee5857f110927d0b45955"

      def install
        bin.install "txtr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/richardwooding/txtr/releases/download/v2.7.2/txtr_2.7.2_darwin_arm64.tar.gz"
      sha256 "6eda46785eddcba3c875acc3d6f069bb0e8d667b94d584dcd5b3f3637e970c67"

      def install
        bin.install "txtr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardwooding/txtr/releases/download/v2.7.2/txtr_2.7.2_linux_amd64.tar.gz"
      sha256 "9bfa956c567e1cf89141f45d38d4c355f4334ee0eb0773f5b664716ea6e9282f"
      def install
        bin.install "txtr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/richardwooding/txtr/releases/download/v2.7.2/txtr_2.7.2_linux_armv6.tar.gz"
      sha256 "47644aa9fe5aea9b31ad8c0c1ee489f347977d5bcf254fd25ae4fbf78d680e1c"
      def install
        bin.install "txtr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardwooding/txtr/releases/download/v2.7.2/txtr_2.7.2_linux_arm64.tar.gz"
      sha256 "2e75593242547295f1ffad6eb3a2e9a03b98d7ec3531a228b10f859413523f0b"
      def install
        bin.install "txtr"
      end
    end
  end

  test do
    system "#{bin}/txtr --version"
  end
end
