# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Txtr < Formula
  desc "GNU strings clone written in Go - extracts printable strings from binary files"
  homepage "https://github.com/richardwooding/txtr"
  version "2.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/richardwooding/txtr/releases/download/v2.10.0/txtr_2.10.0_darwin_amd64.tar.gz"
      sha256 "60ad9942e7f2a656c52cdaa44acacab39965b94e9fdbd0acb07462d0b7e6e76a"

      define_method(:install) do
        bin.install "txtr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/richardwooding/txtr/releases/download/v2.10.0/txtr_2.10.0_darwin_arm64.tar.gz"
      sha256 "a31f97bc50503d6253f2826564b9b8b846259dd56bbc8dec551dc7b5d4d6dcc2"

      define_method(:install) do
        bin.install "txtr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardwooding/txtr/releases/download/v2.10.0/txtr_2.10.0_linux_amd64.tar.gz"
      sha256 "dd2d5f5f8867db72e94a60fc095df939d0743863d80e0baf019104d7254f3ea4"
      define_method(:install) do
        bin.install "txtr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/richardwooding/txtr/releases/download/v2.10.0/txtr_2.10.0_linux_armv6.tar.gz"
      sha256 "02ee53bbd5a1f7faf93ce911d9dec607bb2f10fd4f18188882503f214fbbe638"
      define_method(:install) do
        bin.install "txtr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/richardwooding/txtr/releases/download/v2.10.0/txtr_2.10.0_linux_arm64.tar.gz"
      sha256 "fa478b43df2fb3ee999bedb925be5ae8b56d2a5d1627c5c4b1516e16d527ca30"
      define_method(:install) do
        bin.install "txtr"
      end
    end
  end

  test do
    system "#{bin}/txtr --version"
  end
end
